
export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST'
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS'
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL'

export const ACCOUNT_LIST_REQUEST = 'ACCOUNT_LIST_REQUEST'
export const ACCOUNT_LIST_SUCCESS = 'ACCOUNT_LIST_SUCCESS'
export const ACCOUNT_LIST_FAIL = 'ACCOUNT_LIST_FAIL'


export const ADD_ACCOUNT_TYPE_REQUEST = 'ADD_ACCOUNT_TYPE_REQUEST'
export const ADD_ACCOUNT_TYPE_SUCCESS = 'ADD_ACCOUNT_TYPE_SUCCESS'
export const ADD_ACCOUNT_TYPE_FAIL = 'ADD_ACCOUNT_TYPE_FAIL'


export const ADMIN_DETAILS_REQUEST = 'ADMIN_DETAILS_REQUEST'
export const ADMIN_DETAILS_SUCCESS = 'ADMIN_DETAILS_SUCCESS'
export const ADMIN_DETAILS_FAIL = 'ADMIN_DETAILS_FAIL'