

export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST'
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS'
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL'

export const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST'
export const ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT_DETAILS_SUCCESS'
export const ACCOUNT_DETAILS_FAIL = 'ACCOUNT_DETAILS_FAIL'

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST'
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS'
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL'

export const PENDING_TRANSACTION_LIST_REQUEST = 'PENDING_TRANSACTION_LIST_REQUEST'
export const PENDING_TRANSACTION_LIST_SUCCESS = 'PENDING_TRANSACTION_LIST_SUCCESS'
export const PENDING_TRANSACTION_LIST_FAIL = 'PENDING_TRANSACTION_LIST_FAIL'